### PR TITLE
Ft static design

### PR DESCRIPTION
**Pull request by machariamarigi**
Pull request pertains to the static front end design of the application. The goal was to create wireframes that provide a quick mock up for the application's design. HTML and CSS would later be leveraged to make this designs into actual web pages.

### CODE REVIEW

**Comment by JayKay24** [comment]
I like your folder structure. Good job leveraging bootstrap.

**Comment by AwuorMarvin** [comment]
Looks great...though I think the profile view and bucket list view do the same thing...

**Comment by machariamarigi** [comment]
@AwuorMarvin @JayKay24 Thanks for the reviews. @AwuorMarvin the profile view gives you a list of bucket lists while the bucket list view gives lists all the items in a bucket list.

**Comment by JoshuaOndieki** [comment]
I don't see the purpose of having  high level mockups and low level mockups

**Comment by machariamarigi** [comment]
@JoshuaOndieki thanks for the review. The low-level mock-ups are as close to 'naked' HTML as possible. The helped me to quickly come up with a basic outline for the project, the high-level ones helped me design closer to the final product.

**Pull request merged**
